### ISSUE TITLE
Running in Agent Mode?

### ISSUE THREAD

**Issue by aadrian** [takezoe/gitbucket-ci-plugin#19]
Hi,

Any chance adding an "Agent Mode" for the CI part ?

In "Agent Mode" , the CI tool is running headless on a different machine than the GUI, possibly in the same network. It can also run on more than one machine to distribute build/test load.

The main reason for such requirement is that mostly the CI tool requires Internet access (to be able to fetch build dependencies), whereas GitBucket (and the machine where it runs) is not granted such rights.

Thank you.

**Comment by takezoe** [comment]
That's reasonable, but I intend this plugin is only a simple and temporary solution. It may offer a first step to introduce CI, but If we want to run builds on other machines, we will have to use other authentic tools like Jenkins instead.

**Comment by aadrian** [comment]
> I intend this plugin is only a simple and temporary solution.

I understand.


> but If we want to run builds on other machines

Most of the time, users are simply forced to run the build on a different machine. E.g. besides the Internet access problem, even if GitBucket itself is "light", the projects it can host can be very heavy from a computation point of view, so they need to run on some other faster machine(s).

> we will have to use other authentic tools like Jenkins instead.

We also use for some projects https://www.gocd.org/ since it's less resource intensive than Jenkins, and much easier to use/setup.

P.S.

Since there are so many CI tools however, IMHO this (or another GitBucket CI Plug-in) might have to provide some sort of flexible configuration, like e.g.  **CI REST API mapping** (since all CI tools have REST API), to be able to support most CI Tools with only one plugin.

Creating one GitBucket Plug-in for each CI Tool doesn't looky really feasible.
