### ISSUE TITLE
Error on  Resolving io.github.gitbucket#gitbucket_2.12;4.17.0-SNAPSHOT

### ISSUE THREAD

**Issue by basir** [takezoe/gitbucket-ci-plugin#21]
When I try to run
```
sbt assembly
```
I got this error:
[info] Resolving io.github.gitbucket#gitbucket_2.12;4.17.0-SNAPSHOT ...
[error] Server access Error: Connection timed out: connect url=https://dl.bintray.com/bkromhout/maven/io/github/gitbucket/gitbucket_2.12/4.17.0-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connection timed out: connect url=https://dl.bintray.com/bkromhout/maven/io/github/gitbucket/gitbucket_2.12/4.17.0-SNAPSHOT/gitbucket_2.12-4.17.0-SNAPSHOT.pom
[warn]  module not found: io.github.gitbucket#gitbucket_2.12;4.17.0-SNAPSHOT
[warn] ==== local: tried
[warn]   C:\Users\basir\.ivy2\local\io.github.gitbucket\gitbucket_2.12\4.17.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/github/gitbucket/gitbucket_2.12/4.17.0-SNAPSHOT/gitbucket_2.12-4.17.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\basir\.sbt\preloaded\io.github.gitbucket\gitbucket_2.12\4.17.0-SNAPSHOT\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/basir/.sbt/preloaded/io/github/gitbucket/gitbucket_2.12/4.17.0-SNAPSHOT/gitbucket_2.12-4.17.0-SNAPSHOT.pom
[warn] ==== bintray-bkromhout-maven: tried
[warn]   https://dl.bintray.com/bkromhout/maven/io/github/gitbucket/gitbucket_2.12/4.17.0-SNAPSHOT/gitbucket_2.12-4.17.0-SNAPSHOT.pom
[info] Resolving jline#jline;2.14.3 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.github.gitbucket#gitbucket_2.12;4.17.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```
Could you please let me know how to solve it?

**Comment by takezoe** [comment]
This plugin is developping for the next version of GitBucket (4.17.0). So if you want to build this plugin from source code, you have to do `sbt publish-local` HEAD of GitBucket and run with it. However they are both development version, so I don't recommend to use it actually.

I will release this plugin at the end of this month at the same time of  GitBucket 4.17.0.

**Comment by takezoe** [comment]
GitBucket 4.17.0 and gitbucket-ci-plugin 1.0.0 have been released. You can test  gitbucket-ci-plugin without building from source code any more.
