### ISSUE TITLE
git command not found in build script

### ISSUE THREAD

**Issue by karthikbalu** [takezoe/gitbucket-ci-plugin#43]
build script does not find installed git and displays not found
../build.sh: 5: ../build.sh: git: not found

**Comment by karthikbalu** [comment]
Also it cannot find any binary installed on the gitbucket server host

**Comment by skx** [comment]
What happens if you explicitly setup `PATH` in your script?

ie.

       #!/bin/sh
       PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin
       export PATH
       ...

**Comment by karthikbalu** [comment]
Tried it didnt work same error

The strange issue is, I cant even see/use the git binary with full path too like /usr/bin/git
ls: cannot access 'git': No such file or directory
