### ISSUE TITLE
clean workspace after build

### ISSUE THREAD

**Issue by karthikbalu** [takezoe/gitbucket-ci-plugin#48]
Filling up disk space, to be able to clear workspace after build or limit the stored build results

**Comment by takezoe** [comment]
Currently, build results are kept by up to 20 for each projects. This number is defined at:
https://github.com/takezoe/gitbucket-ci-plugin/blob/e8b09ed0e922e6d99f7680cb49c4fa1e220cf8ce/src/main/scala/io/github/gitbucket/ci/manager/BuildManager.scala#L9

It should be configureble in the admin console.
