### ISSUE TITLE
How can I build a branches on which commit has happened

### ISSUE THREAD

**Issue by bitsmaestro** [takezoe/gitbucket-ci-plugin#52]
We multiple branches now how can I build a branches on which commit has happened

**Comment by takezoe** [comment]
There is no way for now. This plugin can build only a default branch and pull request branches. However I think that multiple branch support is useful. So I consider to make it in the future version.

**Comment by bitsmaestro** [comment]
when are you planning to release "multiple branch build support" in gitbucket-ci-plugin

**Comment by takezoe** [comment]
Sorry, I have no concrete plan for now.
