### ISSUE TITLE
Can't browse files

### ISSUE THREAD

**Issue by chronicals** [takezoe/gitbucket-ci-plugin#59]
The problem occurs with GitBucket 4.23.1 and CI 1.5.0.

When pressing on the "Browse files »" on the builds page of a project, it's not possible to view them, it always says 

URL: `https://giturl/user/project/build/22/workspace/`
```
HTTP ERROR 404
Problem accessing /user/project/build/22/workspace/. Reason:

    Not Found
```

When editing the URL by adding another / in the ending i get the file overview I requested:

URL: `https://giturl/user/project/build/22/workspace//`
```
user / project

Build history > #22 > workspace /

- File 1
- File 2
```

Have I set up something wrong or do I have to change some configuration somewhere? I couldn't find any documentation to this issue, so I think it's a bug.

**Comment by takezoe** [comment]
Thanks for your reporting! It's a bug in the latest version of ci-plugin. I fixed in c29a627679c176fe6cb4bb1209863e935250e1bc and going to release at the same time of GitBucket 4.24.0 next week.
