### ISSUE TITLE
Checkout Submodules

### ISSUE THREAD

**Issue by viceinator** [takezoe/gitbucket-ci-plugin#89]
Hi,
I really like the CI implementation as a plugin in GitBucket instead of an external solution.
But now i have a Problem. For me it is needed to checkout the submodules of the repository to build correclty.
I tried to run `git submodule update --init --recursive` in the build batch but git seems to hang up on that command.
Other commands like `git status` are working perfectly in build batch.
So is it possible to checkout the submodules by general on build or make it possible to run the above git command?

**Comment by takezoe** [comment]
gitbucket-ci-plugin just runs a given script, there is no special stuff regarding git command execution. Does `git submodule update --init --recursive` work from your machine against your GitBucket server?

**Comment by viceinator** [comment]
My GitBucket instance runs on Windows Server 2012 as a Service. The default User for Windows services is the "SYSTEM" user that apparently cannot access the credential manager. So that was my mistake, sorry.
The problem could be resolved by setting another User to run the service.

I close the issue.
